package com.redhat.demo.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Aug 19 16:46:39 EDT 2013
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://ws.demo.redhat.com/", name = "CustomerService")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "printCustomer", targetNamespace = "http://ws.demo.redhat.com/", className = "com.redhat.demo.ws.PrintCustomer")
    @ResponseWrapper(localName = "printCustomerResponse", targetNamespace = "http://ws.demo.redhat.com/", className = "com.redhat.demo.ws.PrintCustomerResponse")
    @WebMethod
    public com.redhat.demo.ws.Customer printCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.redhat.demo.ws.Customer arg0
    );
}
