
/*
 * 
 */

package com.redhat.demo.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Aug 19 16:46:39 EDT 2013
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "CustomerServiceService", 
                  wsdlLocation = "http://simplecustomer-windup.rhcloud.com/simplecustomer/customerservice?wsdl",
                  targetNamespace = "http://ws.demo.redhat.com/") 
public class CustomerServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.demo.redhat.com/", "CustomerServiceService");
    public final static QName CustomerServicePort = new QName("http://ws.demo.redhat.com/", "CustomerServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://simplecustomer-windup.rhcloud.com/simplecustomer/customerservice?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://simplecustomer-windup.rhcloud.com/simplecustomer/customerservice?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CustomerServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "CustomerServicePort")
    public CustomerService getCustomerServicePort() {
        return super.getPort(CustomerServicePort, CustomerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerService
     */
    @WebEndpoint(name = "CustomerServicePort")
    public CustomerService getCustomerServicePort(WebServiceFeature... features) {
        return super.getPort(CustomerServicePort, CustomerService.class, features);
    }

}
